kind: pipeline
name: default

steps: 
- name: build
  image: zssacbbt/docol

- name: wait
  image: postgres:10-alpine
  commands:
  - sleep 60

- name: docker
  image: plugins/docker
  settings:
    username: zssacbbt
    password: Zss1327230
    repo: zssacbbt/docolserver
    tags:
     - latest
     - '1.0.1'
     - '1.0'
  
services:
- name: database
  image: postgres:10-alpine
  ports:
  - 5432
  environment:
    POSTGRES_USER: saisi
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: docol